# Generated by Django 3.0.4 on 2020-03-06 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='screen',
            name='screen_id',
            field=models.IntegerField(default=0),
        ),
    ]
