# Generated by Django 3.0.4 on 2020-03-06 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_screen_screen_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='screen',
            name='id',
        ),
        migrations.AlterField(
            model_name='screen',
            name='screen_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
