# Generated by Django 3.0.4 on 2020-03-06 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20200306_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='screen',
            name='gaming_type',
            field=models.TextField(default='non gaming'),
        ),
    ]
