# Generated by Django 2.1.3 on 2020-03-10 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20200310_2136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='screen',
            name='title',
        ),
    ]
