# Generated by Django 2.1.3 on 2020-03-10 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_screen_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='screen',
            name='time',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
