# Generated by Django 3.0.4 on 2020-03-13 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_screen_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('result_id', models.IntegerField(primary_key=True, serialize=False)),
                ('coder', models.CharField(default='kmz', max_length=200)),
                ('game_name', models.CharField(default='MangoShop', max_length=200)),
                ('screen_id', models.IntegerField()),
                ('gaming', models.IntegerField(default=-1)),
                ('gaming_type', models.TextField(default='non gaming')),
            ],
        ),
        migrations.AddField(
            model_name='screen',
            name='game_name',
            field=models.CharField(default='MangoShop', max_length=200),
        ),
    ]
