# Generated by Django 3.0.4 on 2020-03-13 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20200313_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='result_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
