# Generated by Django 3.0.4 on 2020-03-13 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_auto_20200313_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='screen',
            name='screen_num',
            field=models.IntegerField(default='0'),
        ),
    ]
