# Generated by Django 3.0.4 on 2020-03-14 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_auto_20200313_2051'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coder',
            fields=[
                ('coder', models.CharField(default='kmz_MangoShop', max_length=200, primary_key=True, serialize=False)),
                ('created', models.CharField(default='0000', max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='result',
            name='screen_id',
            field=models.CharField(default='none', max_length=200),
        ),
        migrations.AlterField(
            model_name='screen',
            name='screen_id',
            field=models.CharField(default='none', max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='screen',
            name='screen_num',
            field=models.IntegerField(default='0'),
        ),
    ]
