# Generated by Django 3.0.4 on 2020-03-14 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_auto_20200314_1037'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coder',
            old_name='coder',
            new_name='coder_id',
        ),
    ]
