# Generated by Django 3.0.4 on 2020-03-14 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_auto_20200314_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='coder',
            name='recent_screen_id',
            field=models.CharField(default='none', max_length=200),
        ),
    ]
