# Generated by Django 3.0.4 on 2020-03-14 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_coder_recent_screen_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='screen',
            name='gaming',
        ),
        migrations.RemoveField(
            model_name='screen',
            name='gaming_type',
        ),
        migrations.AddField(
            model_name='result',
            name='result_time',
            field=models.CharField(default='0000', max_length=200),
        ),
    ]
