# Generated by Django 3.0.4 on 2020-03-14 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_auto_20200314_1115'),
    ]

    operations = [
        migrations.RenameField(
            model_name='result',
            old_name='coder',
            new_name='coder_id',
        ),
    ]
